---
grails:
  profile: rest-api
  codegen:
    defaultPackage: mysqltest
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
management:
  endpoints:
    enabled-by-default: false

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8

---

dataSource:
   pooled: true
   jmxExport: true
   dialect: org.hibernate.dialect.MySQL8Dialect
dataSources:
   pipeline:
    url: jdbc:mysql://localhost:3306/recruiter?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username : root
    password : ''
    dbCreate: none
   project:
     url: jdbc:mysql:///recruiter?cloudSqlInstance=central-courier-346722:us-central1:project&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=K3oq70cMP8aJjCaK
     dbCreate: none
   properties:
     jmxEnabled: true
     initialSize: 5
     maxActive: 50
     minIdle: 5
     maxIdle: 25
     maxWait: 10000
     maxAge: 600000
     timeBetweenEvictionRunsMillis: 5000
     minEvictableIdleTimeMillis: 60000
     validationQuery: SELECT 1
     validationQueryTimeout: 3
     validationInterval: 15000
     testOnBorrow: true
     testWhileIdle: true
     testOnReturn: false
     jdbcInterceptors: ConnectionState
     defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED